# Configurações do Banco de Dados H2
spring.datasource.url=jdbc:h2:file:./data/agendafit
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Configurações do Servidor
server.port=8080

# === INTEGRAÇÃO WHATSAPP API ===
whatsapp.api.url=https://api.ultramsg.com/instance180807/
whatsapp.api.token=c4t34bjt3xq9fg3u